# Generated by Otto, do not edit!
#
# This is the Vagrantfile generated by Otto for the development of
# this application/service. It should not be hand-edited. To modify the
# Vagrantfile, use the Appfile.

Vagrant.configure("2") do |config|
  
  if ENV["OTTO_VAGRANT_LAYER_PATH"]
    config.vm.clone = ENV["OTTO_VAGRANT_LAYER_PATH"]
  else
    config.vm.box = "bento/ubuntu-14.04"
    config.vm.box_check_update = false
    config.vm.provider :parallels do |p, o|
      o.vm.box = "parallels/ubuntu-12.04"
    end
  end
  

  # Host only network
  config.vm.network "private_network", ip: "100.69.232.66"

  
  # Setup a synced folder from our working directory to /vagrant
  config.vm.synced_folder '/Users/TheGuy/Sites/ottomigo', "/vagrant",
    owner: "vagrant", group: "vagrant"
  

  # Enable SSH agent forwarding so getting private dependencies works
  config.ssh.forward_agent = true

  # Foundation configuration (if any)
  
  dir = "/otto/foundation-1"
  config.vm.synced_folder '/Users/TheGuy/Sites/ottomigo/.otto/compiled/app/foundation-consul/app-dev', dir
  config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/main.sh"
  

  # ScriptPacks
  dir = "/otto/scriptpacks"
  config.vm.provision "shell", inline: "sudo rm -rf #{dir}; sudo mkdir -p #{dir}; sudo chmod 0777 #{dir}"
  

  # Load all our fragments here for any dependencies.
  
  $preshell = <<SCRIPT
if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update >/dev/null 2>&1
    sudo apt-get install -y apt-transport-https >/dev/null 2>&1
fi
SCRIPT

config.vm.provision "shell", inline: $preshell
config.vm.provision "docker" do |d|
  d.run "mongodb", args: "-p 27017:27017", image: "mongo:3.0"
end

# Sync our own dep folder in there
config.vm.synced_folder '/Users/TheGuy/Sites/ottomigo/.otto/appfile/deps/b80064b1b081e385b5c0cf62e2b2b3f0', "/otto-deps/mongodb-24cbbebc-fc41-53b4-c844-60d642fb523c"

# Foundation configuration for dev dep

dir = "/otto/foundation-mongodb-1"
config.vm.synced_folder '/Users/TheGuy/Sites/ottomigo/.otto/compiled/dep-24cbbebc-fc41-53b4-c844-60d642fb523c/foundation-consul/app-dev-dep', dir
config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/main.sh"



  

  # Use linked clones if possible
  config.vm.provider "virtualbox" do |p|
    p.linked_clone = true
  end

  if Vagrant.has_plugin?("vagrant-parallels", ">= 1.6.0")
    config.vm.provider "parallels" do |p|
      p.linked_clone = true
    end
  end

  # This is to work around some bugs right now
  ["vmware_fusion", "vmware_workstation"].each do |name|
    config.vm.provider(name) do |p|
      p.enable_vmrun_ip_lookup = false
    end
  end

  
  config.vm.provision "shell", inline: $script_app

end




$script_app = <<SCRIPT
set -e

# Make it so that `vagrant ssh` goes directly to the correct dir
echo "cd /vagrant" >> /home/vagrant/.profile

# Configuring SSH for faster login
if ! grep "UseDNS no" /etc/ssh/sshd_config >/dev/null; then
  echo "UseDNS no" | sudo tee -a /etc/ssh/sshd_config >/dev/null
  oe sudo service ssh restart
fi

SCRIPT

